CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_admin TINYINT(1) NOT NULL DEFAULT 0,
    department VARCHAR(80) NOT NULL DEFAULT '',
    pagou TINYINT(1) NOT NULL DEFAULT 0,
    is_paid_pool TINYINT(1) NOT NULL DEFAULT 0,
    emoji VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY emoji (emoji)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS matches (
    id VARCHAR(50) PRIMARY KEY,
    time_a VARCHAR(80) NOT NULL,
    time_b VARCHAR(80) NOT NULL,
    data_hora DATETIME NOT NULL,
    fase VARCHAR(80) NOT NULL,
    grupo VARCHAR(30) NOT NULL,
    tournament_phase VARCHAR(40) NOT NULL DEFAULT 'Fase de Grupos',
    sub_phase VARCHAR(80) NOT NULL DEFAULT '',
    estadio VARCHAR(120) NOT NULL DEFAULT '',
    placar_a TINYINT UNSIGNED NULL,
    placar_b TINYINT UNSIGNED NULL,
    finalizado TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bets (
    id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    match_id VARCHAR(50) NOT NULL,
    palpite_a TINYINT UNSIGNED NOT NULL,
    palpite_b TINYINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bets_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_bets_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE,
    CONSTRAINT uq_bets_user_match UNIQUE (user_id, match_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
